{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mongodb.fullname" . }}-{{ template "mongodb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mongodb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "mongodb.fullname" . }}-list-services
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "mongodb.fullname" . }}-{{ template "mongodb.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ template "mongodb.fullname" . }}-mongodb-role
  apiGroup: ""
{{- end }}
